# Site settings
title: Jamie Afridi - Digital Product Developer
email: j.b.afridi@gmail.com
description: "Jamie Afridi is a digital product developer at MortgageHippo.com focused on product design and Ruby on Rails development. Jamie is based in Chicago, IL."
baseurl: ""
url: "http://jamali.to"

sass:
  sass_dir: assets/stylesheets

# Build settings
markdown: kramdown
permalink: pretty
