# Site settings
title: Jamal Afridi - Senior Product Manager
email: jamal.b.afridi@gmail.com
description: "Jamal Afridi is Senior Product Manager at Avail and focused on product strategy and design. Jamal is based in Chicago, IL."
baseurl: ""
url: "http://www.jamalafridi.com"

sass:
  sass_dir: assets/stylesheets

# Build settings
markdown: kramdown
permalink: pretty

theme: jekyll-theme-cayman