# Site settings
title: Jamal Afridi - Product Manager
email: jamal.b.afridi@gmail.com
description: "Jamal Afridi is a product manager at UrbanBound focused on strategy, design, and Ruby on Rails development. Jamal is based in Chicago, IL."
baseurl: ""
url: "http://jamali.to"

sass:
  sass_dir: assets/stylesheets

# Build settings
markdown: kramdown
permalink: pretty
