# Site settings
title: Jamal Afridi - Digital Product Developer
email: jamal.b.afridi@gmail.com
description: "Jamal Afridi is a digital product developer at MortgageHippo.com focused on product design and Ruby on Rails development. Jamal is based in Chicago, IL."
baseurl: ""
url: "http://jamali.to"

sass:
  sass_dir: assets/stylesheets

# Build settings
markdown: kramdown
permalink: pretty
